version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: app
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "fightCartel2021!"
    ports:
      - "15432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data